[yellow_trip_data_pipeline.destination.filesystem]
bucket_url = "s3://warehouse" # replace with your bucket name,

[yellow_trip_data_pipeline.destination.filesystem.credentials]
aws_access_key_id = "admin" # copy the access key here
aws_secret_access_key = "password" # copy the secret access key here
endpoint_url = "http://minio:9000" # copy your endpoint URL here